trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 7.0'
    inputs:
      packageType: 'sdk'
      version: '7.0.x'
  
  - task: CmdLine@2
    displayName: 'Install .NET MAUI Workload'
    inputs:
      script: 'dotnet workload install maui'

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: 'src/banditoth.MAUI.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build packages'
    inputs:
      command: 'build'
      projects: 'src/banditoth.MAUI.sln'

  - task: CopyFiles@2
    displayName: 'Copy nupkgs to output directory'
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)'
      Contents: '**/*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish built pacakges'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Built packages'
      publishLocation: 'Container'